[2024-06-23T03:01:39.841+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-23T03:01:39.937+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline_dag_with_encryption.get_data_from_bigquery manual__2024-06-23T02:55:34.495783+00:00 [queued]>
[2024-06-23T03:01:39.971+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline_dag_with_encryption.get_data_from_bigquery manual__2024-06-23T02:55:34.495783+00:00 [queued]>
[2024-06-23T03:01:39.978+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 4
[2024-06-23T03:01:40.022+0000] {taskinstance.py:2330} INFO - Executing <Task(BigQueryGetDataOperator): get_data_from_bigquery> on 2024-06-23 02:55:34.495783+00:00
[2024-06-23T03:01:40.163+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline_dag_with_encryption', 'get_data_from_bigquery', 'manual__2024-06-23T02:55:34.495783+00:00', '--job-id', '82', '--raw', '--subdir', 'DAGS_FOLDER/bigquery.py', '--cfg-path', '/tmp/tmp7tsqom_b']
[2024-06-23T03:01:40.177+0000] {standard_task_runner.py:91} INFO - Job 82: Subtask get_data_from_bigquery
[2024-06-23T03:01:40.155+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=4912) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-23T03:01:40.178+0000] {standard_task_runner.py:63} INFO - Started process 4924 to run task
[2024-06-23T03:01:40.482+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_pipeline_dag_with_encryption.get_data_from_bigquery manual__2024-06-23T02:55:34.495783+00:00 [running]> on host 64917a389d59
[2024-06-23T03:01:40.669+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_pipeline_dag_with_encryption' AIRFLOW_CTX_TASK_ID='get_data_from_bigquery' AIRFLOW_CTX_EXECUTION_DATE='2024-06-23T02:55:34.495783+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-23T02:55:34.495783+00:00'
[2024-06-23T03:01:40.675+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-23T03:01:40.730+0000] {connection.py:274} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-06-23T03:01:40.736+0000] {base.py:84} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-06-23T03:01:40.842+0000] {bigquery.py:1046} INFO - Fetching Data from boreal-forest-427103-q9.transformed_1.test max results: 1000
[2024-06-23T03:02:05.790+0000] {connectionpool.py:874} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f366e5ad3d0>: Failed to resolve 'oauth2.googleapis.com' ([Errno -3] Temporary failure in name resolution)")': /token
[2024-06-23T03:02:18.049+0000] {bigquery.py:1088} INFO - Total extracted rows: 1000
[2024-06-23T03:02:18.056+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-23T03:02:18.105+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_pipeline_dag_with_encryption, task_id=get_data_from_bigquery, run_id=manual__2024-06-23T02:55:34.495783+00:00, execution_date=20240623T025534, start_date=20240623T030139, end_date=20240623T030218
[2024-06-23T03:02:18.187+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-23T03:02:18.283+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-23T03:02:18.287+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
