[2024-06-23T02:39:33.298+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-23T02:39:33.314+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline_dag.create_final_data_table manual__2024-06-23T02:38:51.935536+00:00 [queued]>
[2024-06-23T02:39:33.322+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline_dag.create_final_data_table manual__2024-06-23T02:38:51.935536+00:00 [queued]>
[2024-06-23T02:39:33.323+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-23T02:39:33.336+0000] {taskinstance.py:2330} INFO - Executing <Task(BigQueryCreateEmptyTableOperator): create_final_data_table> on 2024-06-23 02:38:51.935536+00:00
[2024-06-23T02:39:33.350+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=4639) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-23T02:39:33.351+0000] {standard_task_runner.py:63} INFO - Started process 4641 to run task
[2024-06-23T02:39:33.351+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline_dag', 'create_final_data_table', 'manual__2024-06-23T02:38:51.935536+00:00', '--job-id', '77', '--raw', '--subdir', 'DAGS_FOLDER/bigquery.py', '--cfg-path', '/tmp/tmpffn0raj_']
[2024-06-23T02:39:33.354+0000] {standard_task_runner.py:91} INFO - Job 77: Subtask create_final_data_table
[2024-06-23T02:39:33.401+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_pipeline_dag.create_final_data_table manual__2024-06-23T02:38:51.935536+00:00 [running]> on host 64917a389d59
[2024-06-23T02:39:33.503+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_pipeline_dag' AIRFLOW_CTX_TASK_ID='create_final_data_table' AIRFLOW_CTX_EXECUTION_DATE='2024-06-23T02:38:51.935536+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-23T02:38:51.935536+00:00'
[2024-06-23T02:39:33.505+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-23T02:39:33.530+0000] {connection.py:274} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-06-23T02:39:33.533+0000] {base.py:84} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-06-23T02:39:33.533+0000] {bigquery.py:1563} INFO - Creating table
[2024-06-23T02:39:34.363+0000] {bigquery.py:1591} INFO - Table final_data.new-data already exists.
[2024-06-23T02:39:34.381+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-23T02:39:34.412+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_pipeline_dag, task_id=create_final_data_table, run_id=manual__2024-06-23T02:38:51.935536+00:00, execution_date=20240623T023851, start_date=20240623T023933, end_date=20240623T023934
[2024-06-23T02:39:34.491+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-23T02:39:34.519+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-23T02:39:34.522+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
