[2024-06-24T02:47:11.660+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-24T02:47:11.753+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_DAG.trigger_encrypt_upload_dag manual__2024-06-24T02:36:36.218790+00:00 [queued]>
[2024-06-24T02:47:11.770+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_DAG.trigger_encrypt_upload_dag manual__2024-06-24T02:36:36.218790+00:00 [queued]>
[2024-06-24T02:47:11.771+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-06-24T02:47:11.805+0000] {taskinstance.py:2330} INFO - Executing <Task(TriggerDagRunOperator): trigger_encrypt_upload_dag> on 2024-06-24 02:36:36.218790+00:00
[2024-06-24T02:47:11.814+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=161) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-24T02:47:11.817+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ETL_DAG', 'trigger_encrypt_upload_dag', 'manual__2024-06-24T02:36:36.218790+00:00', '--job-id', '188', '--raw', '--subdir', 'DAGS_FOLDER/etl_dags.py', '--cfg-path', '/tmp/tmpxv0_eu39']
[2024-06-24T02:47:11.820+0000] {standard_task_runner.py:63} INFO - Started process 162 to run task
[2024-06-24T02:47:11.821+0000] {standard_task_runner.py:91} INFO - Job 188: Subtask trigger_encrypt_upload_dag
[2024-06-24T02:47:11.907+0000] {task_command.py:426} INFO - Running <TaskInstance: ETL_DAG.trigger_encrypt_upload_dag manual__2024-06-24T02:36:36.218790+00:00 [running]> on host 33e391cc0777
[2024-06-24T02:47:12.043+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ETL_DAG' AIRFLOW_CTX_TASK_ID='trigger_encrypt_upload_dag' AIRFLOW_CTX_EXECUTION_DATE='2024-06-24T02:36:36.218790+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-24T02:36:36.218790+00:00'
[2024-06-24T02:47:12.045+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-24T02:47:12.241+0000] {trigger_dagrun.py:222} INFO - Waiting for transforma_carga_bigquery on 2024-06-24 02:47:12.092335+00:00 to become allowed state ['success'] ...
[2024-06-24T02:48:14.421+0000] {trigger_dagrun.py:222} INFO - Waiting for transforma_carga_bigquery on 2024-06-24 02:47:12.092335+00:00 to become allowed state ['success'] ...
[2024-06-24T02:49:16.365+0000] {trigger_dagrun.py:222} INFO - Waiting for transforma_carga_bigquery on 2024-06-24 02:47:12.092335+00:00 to become allowed state ['success'] ...
[2024-06-24T02:50:16.393+0000] {trigger_dagrun.py:222} INFO - Waiting for transforma_carga_bigquery on 2024-06-24 02:47:12.092335+00:00 to become allowed state ['success'] ...
[2024-06-24T02:51:21.746+0000] {trigger_dagrun.py:222} INFO - Waiting for transforma_carga_bigquery on 2024-06-24 02:47:12.092335+00:00 to become allowed state ['success'] ...
[2024-06-24T02:52:21.770+0000] {trigger_dagrun.py:222} INFO - Waiting for transforma_carga_bigquery on 2024-06-24 02:47:12.092335+00:00 to become allowed state ['success'] ...
[2024-06-24T02:53:21.788+0000] {trigger_dagrun.py:222} INFO - Waiting for transforma_carga_bigquery on 2024-06-24 02:47:12.092335+00:00 to become allowed state ['success'] ...
[2024-06-24T02:53:47.938+0000] {local_task_job_runner.py:310} WARNING - State of this instance has been externally set to removed. Terminating instance.
[2024-06-24T02:53:47.978+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-24T02:53:48.006+0000] {process_utils.py:132} INFO - Sending 15 to group 162. PIDs of all processes in the group: [162]
[2024-06-24T02:53:48.012+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 162
[2024-06-24T02:53:48.022+0000] {taskinstance.py:2611} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-06-24T02:53:48.042+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-24T02:53:48.429+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=162, status='terminated', exitcode=0, started='02:47:11') (162) terminated with exit code 0
